services:
  - docker

language: shell

rust:
  - stable


script:
  - docker build -t terminusdb/terminus_store_prolog:latest .
  - docker run -it --rm terminusdb/terminus_store_prolog:latest bash -c "./run_swipl -g run_tests -g halt"

deploy:
  provider: script
  script: bash deploy.sh
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    secure: oJJQMy2N8R86R6Vr54jkoe9hNz/2teHiibAEQf92bTM4lFpVugsccIpInT7rwkyJ7UMSueWkTLEooqCHYAZsDck0W4RACMozUEwkO3HT+JLmlmmYtYHxxYboxdjfakXKmv6hAxNJba05zJ5/YSVdI5nxvlgC65rY3ved9rWVAhfoTNqid78AtPTvORO7l+nVg1Wq6T/EOR9A/7MbIlh0DIxrl0A/5sw/vpZN1LY7+7YvIb8LrV9TTkSWe4B2Vqvq2szgGlkdjv+ZaeFoj/R8ECgnDYh/ZZ5JL8rzmH4IS36sBbXFmuRdp7o834awmNkm3PnyvNEm5NZD/tMP6Yu2iOuGhSsM5bIswgaUSsRXxX3yDGSJQoSg7uzMs8QV5uDXcXD68I0WpJPIcCMBWt1xyNVRr8eHLUDBOvEEvmTK9gYcoylpqqawy0akzz+ksVAnX73ALmQzFxKU31yuRE2s002snOz8KfXOOmnS2uW2EtU5+rgw9GwbGgRoPqiSbCa/J/lpcR6m7thY/PYxuHh2UOhlK+3vAIyTQlBUi+JVyZI4XdS/+YiYZp3tsq6vzyXjewwzGe2gp2qNcyvJpbhbdOCuN3EFdZ4i2upOx9uuP4MXQ5/5jGvCes89GtlAh5B8ELST/fhu51QvhgcAGDTcmRWn+JXZxzzf/FMXjzLrCEY=
