language: rust

rust:
  - stable

before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox autoconf libtool build-essential

script:
  - ./make
  - ./run_swipl -g run_tests -g halt
  - ./run_swipl -g "show_coverage(run_tests)" -g halt

deploy:
  provider: script
  script:
    - echo "pack_install('https://github.com/terminusdb/terminus_store_prolog/archive/${TRAVIS_TAG}.zip', [interactive=false])." | swipl
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    secure: oJJQMy2N8R86R6Vr54jkoe9hNz/2teHiibAEQf92bTM4lFpVugsccIpInT7rwkyJ7UMSueWkTLEooqCHYAZsDck0W4RACMozUEwkO3HT+JLmlmmYtYHxxYboxdjfakXKmv6hAxNJba05zJ5/YSVdI5nxvlgC65rY3ved9rWVAhfoTNqid78AtPTvORO7l+nVg1Wq6T/EOR9A/7MbIlh0DIxrl0A/5sw/vpZN1LY7+7YvIb8LrV9TTkSWe4B2Vqvq2szgGlkdjv+ZaeFoj/R8ECgnDYh/ZZ5JL8rzmH4IS36sBbXFmuRdp7o834awmNkm3PnyvNEm5NZD/tMP6Yu2iOuGhSsM5bIswgaUSsRXxX3yDGSJQoSg7uzMs8QV5uDXcXD68I0WpJPIcCMBWt1xyNVRr8eHLUDBOvEEvmTK9gYcoylpqqawy0akzz+ksVAnX73ALmQzFxKU31yuRE2s002snOz8KfXOOmnS2uW2EtU5+rgw9GwbGgRoPqiSbCa/J/lpcR6m7thY/PYxuHh2UOhlK+3vAIyTQlBUi+JVyZI4XdS/+YiYZp3tsq6vzyXjewwzGe2gp2qNcyvJpbhbdOCuN3EFdZ4i2upOx9uuP4MXQ5/5jGvCes89GtlAh5B8ELST/fhu51QvhgcAGDTcmRWn+JXZxzzf/FMXjzLrCEY=
