language: rust

rust:
  - stable

before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox autoconf libtool build-essential

script:
  - make
  - swipl -g run_tests -g halt ./prolog/terminus_store.pl
  - swipl -g "show_coverage(run_tests)." -g halt prolog/terminus_store.pl
