language: rust

env:
  - PACKSODIR=lib
  - CFLAGS='-fPIC -pthread -I"/usr/local/lib/swipl/include" -I"/usr/lib/swipl/include"'
  - SOEXT='so'
  - CC=gcc

rust:
  - stable

before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox autoconf libtool build-essential

script:
  - PACKSODIR='make
  - swipl -g run_tests -g halt ./prolog/terminus_store.pl
  - swipl -g "show_coverage(run_tests)." -g halt prolog/terminus_store.pl

deploy:
  provider: script
  script:
    - echo "pack_install('https://github.com/terminusdb/terminus_store_prolog.git', [interactive=false])." | swipl
  on:
    tags: true
  skip_cleanup: true
