language: rust

env:
  - PACKSODIR=lib CFLAGS='-fPIC -pthread -I"/usr/lib/swi-prolog/include"' SOEXT='so' CC=gcc

rust:
  - stable

before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox autoconf libtool build-essential

script:
  - make
  - swipl -g "assertz(file_search_path(foreign,'$PWD/lib'))" -g "['./prolog/terminus_store.pl']" -g run_tests -g halt
  - swipl -g "assertz(file_search_path(foreign,'$PWD/lib'))" -g "['./prolog/terminus_store.pl']" -g "show_coverage(run_tests)" -g halt

deploy:
  provider: script
  script:
    - echo "pack_install('https://github.com/terminusdb/terminus_store_prolog/${TRAVIS_TAG}.zip', [interactive=false])." | swipl
  on:
    tags: true
  skip_cleanup: true
