[package]
name = "terminus-store-prolog"
version = "0.1.0"
authors = ["Matthijs van Otterdijk <matthijs@datachemist.com>", "Robin de Rooij <robin@datachemist.com>"]
edition = "2018"

[lib]
name = "terminus_store_prolog"
crate-type = ["cdylib"]

[dependencies]
terminus-store = { git = "https://github.com/terminusdb/terminus-store", tag="v0.1.0" }
