language = "C"

sys_includes = ["stdbool.h"]
no_includes = true

[export]
include = ["LayerAndParent"]

[export.rename]
"SyncStoreLayerBuilder" = "void"
"SyncStoreLayer" = "void"
"SyncNamedGraph" = "void"
"SyncStore" = "void"
