name: Publish

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t terminusdb/terminus_store_prolog:latest .

      - name: Run tests
        run: docker run --rm terminusdb/terminus_store_prolog:latest bash -c "./run_swipl -g run_tests -g halt"

      - name: Log into Docker Container Registry
        if: github.event_name != 'pull_request' && (contains(github.ref, 'tag') || contains(github.ref, 'master'))
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u terminusdb --password-stdin

      - name: Push to the Docker registry
        if: github.event_name != 'pull_request' && (contains(github.ref, 'tag') || contains(github.ref, 'master'))
        run: |
          IMAGE_ID=$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  windows:
    runs-on: windows-latest
    env:
      RUSTFLAGS: -C target-feature=+crt-static
    steps:
      - uses: actions/checkout@v2
        # Runs a single command using the runners shell
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Install SWI Prolog
        run: choco install swi-prolog

      - name: Compile terminus-store-prolog
        shell: bash
        run: |
          export PATH=$PATH:/c/Program\ Files/swipl/bin/
          make WIN_TERMINUS_STORE_PROLOG_PATH=./rust/target/release WIN_SWIPL_INCLUDE='/c/Program Files/swipl/include/' windows_release

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        # Runs a single command using the runners shell
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Install SWI Prolog
        run: brew install swi-prolog

      - name: Compile terminus-store-prolog
        shell: bash
        run: |
          ./make.sh

      - name: Upload macOS artifact dylib
        uses: actions/upload-artifact@v1
        with:
          name: libterminus_store.dylib
          path: lib/x86_64-darwin/libterminus_store.dylib
