name: Publish

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t terminusdb/terminus_store_prolog:latest .

      - name: Run tests
        run: docker run --rm terminusdb/terminus_store_prolog:latest bash -c "./run_swipl -g run_tests -g halt"
